all:
	@make -C ./ex00 --no-print-directory
	@make -C ./ex01 --no-print-directory
	@make -C ./ex02 --no-print-directory

clean:
	@make -C ./ex00 clean --no-print-directory
	@make -C ./ex01 clean --no-print-directory
	@make -C ./ex02 clean --no-print-directory

fclean:
	@make -C ./ex00 fclean --no-print-directory
	@make -C ./ex01 fclean --no-print-directory
	@make -C ./ex02 fclean --no-print-directory

re:
	@make -C ./ex00 re --no-print-directory
	@make -C ./ex01 re --no-print-directory
	@make -C ./ex02 re --no-print-directory

test:
	@clear
	@echo ""
	@echo "************************************"
	@echo "************ EX00 TEST *************"
	@echo "************************************"
	@echo ""
	@make -C ./ex00 test --no-print-directory
	@echo ""
	@echo "************************************"
	@echo "************ EX01 TEST *************"
	@echo "************************************"
	@echo ""
	@make -C ./ex01 test --no-print-directory
	@echo ""
	@echo "************************************"
	@echo "************ EX02 TEST *************"
	@echo "************************************"
	@echo ""
	@make -C ./ex02 test --no-print-directory